version: "3.8"
services:
  db:
    container_name: "shopping-list-db"
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - db:/db
    ports:
      - "5432:5432"
    networks:
      - app
#
#  client:
#    build:
#      dockerfile: Dockerfile
#    command: sh -c "./run-next-dev.sh"
#    volumes:
#      - ./:/user/src/app
#    ports:
#      - "3000:3000"
#    networks:
#      - app

volumes:
   db:
    name: 'shopping-list'

networks:
  app:

